---
# The 'include' property defines specific board/shield combinations to build.
# For ZMK, the keymap file name is assumed to be <shield_name>.keymap or <board_name>.keymap
# unless the 'keymap' property is specified.
include:
  # QWERTY BT (Assuming your charybdis.keymap has the QWERTY layout)
  - board: nice_nano_v2
    shield: charybdis_left
    format: bt
    artifact-name: charybdis_left
    
  - board: nice_nano_v2
    shield: charybdis_right
    format: bt
    artifact-name: charybdis_right
    # Note: Removed the conflicting 'snippet: studio-rpc-usb-uart' line.

  # Colemak DH BT (If you have a separate keymap file named colemak_dh.keymap)
  - board: nice_nano_v2
    shield: charybdis_left
    keymap: colemak_dh  # Only include if you have 'config/colemak_dh.keymap'
    format: bt
    artifact-name: charybdis_colemak_dh_left

  - board: nice_nano_v2
    shield: charybdis_right
    keymap: colemak_dh  # Only include if you have 'config/colemak_dh.keymap'
    format: bt
    artifact-name: charybdis_colemak_dh_right

  # Firmware Reset
  - board: nice_nano_v2
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_nano_v2
